### PR TITLE
WIP: Update the shipper metadata after each upload

### PR DESCRIPTION
**Pull request by SuperQ**
## Changes

Update the shipper metadata after each upload rather than waiting to the end of the sync.

Partly fixes https://github.com/improbable-eng/thanos/issues/934

## Verification

Not tested yet.

### CODE REVIEW

**Comment by bwplotka** [comment]
So essentially you would like to have updated meta.json lying around? hmm useful for manual upload of blocks as well. Worth to double check in some e2e/integration test at some point that Prometheus can still read that meta, but otherwise.. it might be fine.

Why is that required though?

**Comment by SuperQ** [comment]
See the linked issue. The shipper iterates over all of the compacted blocks in one go, we're uploading ~6 months of week-size blocks. So if one of the couple dozen blocks gets a storage error, all of the previously uploaded blocks don't get marked as complete. Then it retries and finds all of the previously uploaded OK blocks as overlapping.

**Comment by SuperQ** [comment]
Yea, this doesn't work as expected, it drops all blocks after the the last block upload.

**Comment by SuperQ** [comment]
This is the wrong fix.

**Pull request closed without merging**
