### PR TITLE
store: Setting the start and end to prior posting changes

### PR DESCRIPTION
**Pull request by domgreen**

### CODE REVIEW

**Comment by domgreen** [comment]
I'm still unsure if we should be adding `maxChunkSize`/`maxSeriesSize` onto the `end` parameter when calling `loadChunks`/`loadSeries` functions the `rng(k)` func already adds this ... could be a minor detail.

**Comment by bwplotka** [comment]
This is it! Will add unit test for this into your branch.

> `maxChunkSize`/`maxSeriesSize` onto the `end` parameter when calling `loadChunks`/`loadSeries`

I agree - it might be a bug as well, will remove it. We can always add it. Test should catch this hopefully.

**Comment by bwplotka** [comment]
Added test with naive "partitioner" to simulate multiple parts. This on master triggers:

`runtime error: slice bounds out of range` - on this branch it works. Awesome :+1:

**Comment by bwplotka** [comment]
And yea, that extra `maxSeries/ChunkSize` is definitely bug on new version - since we moved to what parts gives us, we should avoid this. Added commit fixing this as well.

**Comment by bwplotka** [comment]
Thanks for spotting this :+1:  Classic golang bug :man_facepalming: function closure + loop... :boom:

**Comment by bwplotka** [comment]
Fixes https://github.com/improbable-eng/thanos/issues/829

**Comment by domgreen** [comment]
> Thanks for spotting this  Classic golang bug  function closure + loop...

@devnev spotted it within seconds :joy:

**Pull request merged**
