### PR TITLE
add CHANGELOG entry for PR #1311

### PR DESCRIPTION
**Pull request by wbh1**
## Changes

Adds an entry to the CHANGELOG for the fix added in #1311, since I overlooked that initially :sweat_smile: 

## Verification

N/A

### CODE REVIEW

**Comment by wbh1** [comment]
@povilasv :smile:

**Comment by wbh1** [comment]
It could be many different things causing the panics, honestly. Network connectivity, Azure availability, etc. It was caused by the Azure library having a part of a function that wasn't checking the value of `err` before proceeding to its next step.

I could clarify that the panics would happen while downloading the "blob" to a buffer, if that helps :)

**Comment by bwplotka** [comment]
Ah. so let's write then `not checked errors` to be explicit (:

**Comment by wbh1** [comment]
Fixed it. 

PS - congrats on CNCF acceptance :tada:

**Pull request merged**
