### PR TITLE
objstore: Increase the response header timeout in the S3 provider to 2 minutes and make it configurable

### PR DESCRIPTION
**Pull request by antonio**
## Changes

This PR increases the response header timeout in the S3 provider from 15 seconds (introduced in #323) to 2 minutes, an arbitrary number that I've found works well with large blocks as a result of debugging #318. This has solved my recurring problems with the `net/http: timeout awaiting response headers` error.

I'm not sure whether a fixed number like this or having a configuration flag is better: while the latter is more flexible I believe it introduces complexity and does not provide much value. I'm happy to update this if that's the preferred solution, though.

## Verification

I have been running three different compactor processes against a few buckets that would always fail to be compacted with the aforementioned error, and haven't seen a single error in 4 days.

### CODE REVIEW

**Comment by midnightconman** [comment]
This seems very similar to https://github.com/improbable-eng/thanos/pull/567, can you explain the difference between the two options?

**Comment by antonio** [comment]
@povilasv @bwplotka thank you for your feedback, I'll make the rest of the HTTP options configurable in the same way that it's done in the PR that @midnightconman linked to.

**Comment by antonio** [comment]
@povilasv @bwplotka I think this is ready for another :eyes:

I've decided to only make that one option configurable in the end as opposed to make every `HTTPTransport` timeout configurable to not add extra complexity, but could do the latter if you feel different.

I've refactored the tests to make it a little bit more clear what the default values are for the HTTP client, and reworded some parts of the documentation while I dropped a line about this new option.

**Comment by GiedriusS** [comment]
:tada: thank you :heart:

**Pull request merged**
