### PR TITLE
included docker push on Makefile + added push of successful master builds

### PR DESCRIPTION
**Pull request by V3ckt0r**
@Bplotka @fabxc 

Please could you review changes.  Hopefully this will address having to manually update the docker images #227 and help towards the release workflow #214 

We will need to add the $DOCKER_USERNAME" and "$DOCKER_PASSWORD environment variables to the Travis job for this to work. https://docs.travis-ci.com/user/environment-variables/

You can see an example build here https://travis-ci.org/V3ckt0r/thanos/jobs/348643561

cheers

### CODE REVIEW

**Comment by Bplotka** [comment]
Hey, 
This is unfortunate, but we switched to CircleCI recently... because of various reasons. Thanks for doing it, but could you please adapt that to CircleCI? ^^ 

I think I like this idea, can setup these PASSWORD/USER for you then.

**Comment by V3ckt0r** [comment]
No worries, I've adapted the same for CircleCi, please see PR #235

**Comment by Bplotka** [comment]
So can we close this one if we have nice shiny new PR? Thanks!

**Comment by V3ckt0r** [comment]
Yup

**Pull request closed without merging**
