### PR TITLE
Marked remote receiver proposal as complete

### PR DESCRIPTION
**Pull request by bwplotka**

### CODE REVIEW

**Comment by domgreen** [comment]
Is this complete? I think that the first PR is in but not completed to the proposal

**Comment by bwplotka** [comment]
What's missing?

I think we miss a convention for github issues that tracks those proposals ):

**Comment by brancz** [comment]
Pretty much only a single-tenant, non-sharded receiver is done.

**Comment by bwplotka** [comment]
Let's wait with this then. ;p

**Pull request closed without merging**
