### PR TITLE
Increased gRPC max msg size for client recv to the maximum possible (2GB)

### PR DESCRIPTION
**Pull request by Bplotka**
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by Bplotka** [comment]
Maybe worth to add some histogram for message sizes?

**Comment by fabxc** [comment]
👍  Yea, a histogram could be insightful.

**Comment by fabxc** [comment]
Mh, wouldn't it be much cheaper and less invasive to just do a final count of the combined size of chunks right before sending them [here](https://github.com/improbable-eng/thanos/blob/master/pkg/store/bucket.go#L610)?

**Comment by fabxc** [comment]
👍

**Pull request merged**
