### PR TITLE
makefile: Excluded tencent doc check.

### PR DESCRIPTION
**Pull request by bwplotka**
China firewall does not like our CI check it causes flakes - excluding.

Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by adrien-f** [comment]
Would that be a one shot ? Will there be others links to exclude ? Might be worth to make a list and use that instead of hardcoded strings ? YAGNI ?

**Comment by bwplotka** [comment]
For now I have seen only this one for at least 10x times. If it will more than one then we can make it nicer (:

**Comment by jojohappy** [comment]
@bwplotka Could we use the domain `intl.cloud.tencent.com` instead of `cloud.tencent.com`? Could you help me to run `make check-docs` with that?

**Comment by bwplotka** [comment]
Why is that better?

**Comment by jojohappy** [comment]
@bwplotka That domain seems to be used for international site and written by English, I think it will be good for international user. But I could not verify the result.

**Pull request merged**
