### PR TITLE
store/sidecar: use minio-go version that support ap-east-1

### PR DESCRIPTION
**Pull request by cjohnston-fuze**
## Changes

Update minio-go to pseudo-version that support new ap-east-1 region.

## Verification

Applied to v0.4.0 tag and confirmed its now connecting to ap-east-1 dualstack endpoint instead of the default us-east-1.

### CODE REVIEW

**Comment by bwplotka** [comment]
have you run `go mod tidy` or `go mod verify` after change?

**Comment by cjohnston-fuze** [comment]
Sorry I'm not very familiar with go. I do see the changes to go.sum are automatic and have made that commit.

**Comment by GiedriusS** [comment]
If it's not a problem then maybe we could wait until the next official release? Then we'd be able to also add error-only tracing to our S3 client which is amazing :heart_eyes:

**Comment by bwplotka** [comment]
Up to you - I am happy to brough this unless you are concerned @GiedriusS

**Comment by xjewer** [comment]
>Then we'd be able to also add error-only tracing to our S3 client which is amazing 😍

and this change https://github.com/minio/minio-go/pull/1104

**Pull request merged**
