### PR TITLE
sidecar: Add support for prometheus with --web.route-prefix.

### PR DESCRIPTION
**Pull request by Bplotka**
Fixes https://github.com/improbable-eng/thanos/issues/478

Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by xjewer** [comment]
LGTM

**Comment by brancz** [comment]
This is something we've struggled to communicate properly on upstream Prometheus. I'm not sure how, but the flag of the sidecar could use another sentence I think to make clear that this is not necessarily the same as the `external-url` in Prometheus, but rather the `route-prefix` and the route-prefix defaults to the path of the `external-url` (but can be explicitly set). Not sure if this is helpful or more confusing to new users.

Otherwise this lgtm

**Comment by Bplotka** [comment]
Yea @brancz , I totally see the issue. We don't want to go through public load balancer etc for sidecar traffic... (: 

Let's merge this to unblock people. I added comment to make sure it is an URL that goes over local network.

**Comment by brancz** [comment]
sounds good to me

**Pull request merged**
