### PR TITLE
makefile: Added force-deps command.

### PR DESCRIPTION
**Pull request by Bplotka**
Related: https://github.com/improbable-eng/thanos/issues/449

Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
    

## Verification

Local

### CODE REVIEW

**Comment by domgreen** [comment]
Actually ... am i being a fool?
```
➜  thanos git:(1858548) make vendor
>> dep ensure
grouped write of manifest, lock and vendor: failed to export google.golang.org/grpc: fatal: failed to unpack tree object 168a6198bcb0ef175f7dacec0b8691fc141dc9b8
: exit status 128
make[1]: *** [force-deps] Error 1
make: *** [vendor] Error 2
```

**Comment by Bplotka** [comment]
@prabhakm you don't have `/Users/xxxxxx/goprojects/bin/` for some reason

**Comment by Bplotka** [comment]
@prabhakm  I feel like you need just mkdir bin directory

**Comment by Bplotka** [comment]
Fixed in different PR.

**Pull request closed without merging**
