### PR TITLE
Update to go1.11.1 and move to modules

### PR DESCRIPTION
**Pull request by domgreen**
## Changes

Updating to go1.11.1 and modules ... experimental change. Locally works well but want to test CI.

- also had to update the recent azure and ignoring an error check ... may fail the build

## Verification

Currently able to run `make all` locally

### CODE REVIEW

**Comment by domgreen** [comment]
Currently blocked on our usage of `errcheck` as it currently does not support `go mod` ... issue has been filed https://github.com/kisielk/errcheck/issues/155

**Comment by sylr** [comment]
Hey @domgreen, could we move forward with this ?

**Comment by domgreen** [comment]
@sylr feel free to pick this up, the `errcheck` issue seems to be fixed now 👍

**Comment by domgreen** [comment]
Should also look at bumping to `go1.11.5`

**Comment by sylr** [comment]
All right I'll see what I can do tomorrow 👍

**Pull request closed without merging**
