### PR TITLE
Vendor dependencies

### PR DESCRIPTION
**Pull request by mattbostock**
I was going to raise an issue, but figured a pull request would also prompt discussion and save you the work if it's not contentious :-)

* * *

Vendoring dependencies by checking in the dependencies is standard
practice for Go projects. In particular, it removes any dependency on
the network or dep itself when building the project.

Adds prune settings to `Gopkg.toml` to keep the number of added files to
a minimum.

### CODE REVIEW

**Comment by Bplotka** [comment]
Yea we just resigned from this: https://github.com/improbable-eng/thanos/pull/202 (: 

Can we postpone it to the point when it will be really necessary? I think we are aware that this might be helpful in some cases, but:
- checking in someones else code feels really bad.
- repo is bigger than it should
- Changing dependencies will be really really difficult: Our PRs will be obfuscated OR we will need to stack them which is not easy in Github.
- we we basically kill any sense in Github Graphs  ^^

I am not fan of this, but if that's necessary...  What do you think @fabxc?

BTW: We need to set up some CI for external contributors. Travis does not support that. ):

**Comment by mattbostock** [comment]
If it helps, the prune settings make a big difference. #202 added 6,000+ files, this PR adds 1,461 files.

Another advantage of vendoring dependencies is, assuming no other obstacles, it makes Thanos work with `go get` _and_ with the expected versions of dependencies.

**Comment by Bplotka** [comment]
Yup, `prune` is cool, but still my mentioned problems remain.

Regarding `go get`: true, but on the other hand I think one more step to install source code is not a blocker for us. (:

Also, hopefully https://research.swtch.com/vgo-intro will fix the situation and will be supported by `go get`  (:

**Comment by mattbostock** [comment]
Ok, closing as this will quickly become out of date if it's not desired.

**Pull request closed without merging**
