### PR TITLE
A little elaboration about on [min/max]-block-duration documentation.

### PR DESCRIPTION
**Pull request by homelessnessbo**
MR grew out from this thread https://improbable-eng.slack.com/archives/CA4UWKEEN/p1553679266828300. 

TLDR: end users, like me, get confused by `prometheus_tsdb_compactions_total` being incremented and Prometheus logs about compaction when internal Prometheus compaction is supposed to be disabled, so there's a little elaboration for that.

I haven't found a better place in the repo to put this piece of information, tell me if there is such.

### CODE REVIEW

**Comment by GiedriusS** [comment]
Perhaps we should mention that with https://github.com/improbable-eng/thanos/pull/838 being merged we will check this automatically? So it's not just a recommendation, but a requirement. What do you think?

**Comment by homelessnessbo** [comment]
This PR is definitely worthy to mention since it has a direct relation to the topic, but I'd argue with  "a requirement" statement.  Running Thanos with  `sidecar.validate-prom` is optional and up to end user so as running compactor itself. There might be quite successful set-up cases without compactor at all, and AFAIK (correct me if I'm wrong) - things will be working with any initial block size in a relatively successful way with obvious downside when the set-up has a really old and huge bunch of data.

Should I make a PR to PR with corresponding changes?

**Comment by yeya24** [comment]
Awesome! It is worthy for clarifying that.

**Comment by bwplotka** [comment]
Just put those changes in this very PR @homelessnessbo (: It's small enough.

**Comment by homelessnessbo** [comment]
👍 Will include it in #838 in a few minutes

**Comment by homelessnessbo** [comment]
https://github.com/yeya24/thanos/pull/1/files

**Pull request closed without merging**
