### PR TITLE
Added flag to disable gossip explicitly.

### PR DESCRIPTION
**Pull request by bwplotka**
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by FUSAKLA** [comment]
This is great, finally the noise in logs will stop :+1:

**Comment by adrien-f** [comment]
Looks nice :+1: Small nitpick on the naming of `stateFetcher` but that might be just me !

**Comment by bwplotka** [comment]
>  Small nitpick on the naming of stateFetcher but that might be just me !

What nitpick? We can improve the naming it if we can find better name for this (:

**Comment by adrien-f** [comment]
It just felt weird to add a new component name but on a second read, it clicks :+1: !

**Comment by bwplotka** [comment]
> Will there be any other Gossip/Peering implementations ?

You mean for fileSD?

**Pull request merged**
