### PR TITLE
Remove some white noise

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <764524258@qq.com>

## Changes

Delete all duplicate blank in docs.

### CODE REVIEW

**Comment by domgreen** [comment]
Did you run make after this? I wonder if our `make docs` step is actually adding this white space? Can you double check and I can have a look when I'm at my laptop.

**Comment by GiedriusS** [comment]
Thank you for contribution! However, `make docs` adds these automatically for some reason. Could you check it out? The CI fails because of it now :(

**Comment by daixiang0** [comment]
@domgreen @GiedriusS i make failed from my branch:
```
$ make docs
>> formatting code
go: verifying github.com/grpc-ecosystem/go-grpc-middleware@v1.0.0: checksum mismatch
	downloaded: h1:BWIsLfhgKhV5g/oF34aRjniBHLTZe5DNekSjbAjIS6c=
	go.sum:     h1:Iju5GlWwrvL6UBg4zJJt3btmonfrMlCDdsejg4CZE7c=
```
switch to upstream/master, still failed, post in [slack](https://improbable-eng.slack.com/archives/CA4UWKEEN/p1553059894585700) but no feedback.

**Comment by daixiang0** [comment]
@domgreen @GiedriusS i find root [cause](https://github.com/alecthomas/kingpin/issues/267)

so wait upstream fix it or i can change genflagdocs.sh to remove white noise.

**Pull request merged**
