### PR TITLE
Add Qonto logo

### PR DESCRIPTION
**Pull request by AlexisSellier**
Add Qonto as a Thanos user !

### CODE REVIEW

**Comment by povilasv** [comment]
@AlexisSellier it is live https://thanos.io/ :1st_place_medal:

**Comment by AlexisSellier** [comment]
Thanks a lot @povilasv

**Comment by bwplotka** [comment]
Can you share optionally @AlexisSellier anything about setup size, deployment model, after and cloud provider if any? (:

**Comment by AlexisSellier** [comment]
In summary, everything run on AWS. We have 6 Kubernetes cluster (not EKS but kubesprayed) with one prometheus per cluster. The sidecar is installed using the prometheus operator. 

I was asking myself if it was worth to write an article on our Blog to describe all the architecture (I do not know if there is a lot a material about Thanos on the web and do not want to be redundant). I could give more information that way. Tell me if it is worth for you in term of visibility.

**Pull request merged**
